/** Public paths — real trip photos from the WordPress archive. */
export const galleryImagePaths: readonly string[] = [
  "/gallery/01.jpeg",
  "/gallery/02.jpeg",
  "/gallery/03.jpeg",
  "/gallery/04.jpeg",
  "/gallery/05.jpeg",
  "/gallery/06.jpeg",
  "/gallery/07.jpeg",
  "/gallery/08.jpeg",
  "/gallery/09.jpeg",
  "/gallery/11.jpeg",
  "/gallery/12.jpeg",
  "/gallery/13.jpeg",
  "/gallery/15.jpg",
  "/gallery/16.jpg",
  "/gallery/17.jpg",
  "/gallery/18.jpg",
  "/gallery/19.jpg",
  "/gallery/21.jpeg",
  "/gallery/22.jpeg",
  "/gallery/23.jpg",
  "/destinations/passu-cones.jpg",
  "/destinations/naltar-valley.jpg",
  "/destinations/kutwal-valley.jpg",
  "/tours/fairy-meadows-3.jpg",
];
